version: "3.1"

services:
  db:
    image: postgres:13.1
    restart: always
    container_name: db
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DBUser}
      - POSTGRES_PASSWORD=${DBPassword}
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    environment:
      - POSTGRES_USER=${DBUser}
      - POSTGRES_PASSWORD=${DBPassword}