version: "3.1"

services:
  api:
    build: .
    restart: always
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - "db"
  db:
    image: postgres:13.1
    restart: always
    container_name: db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Cabin2021
      - POSTGRES_DB=Weather
      - PGDATA=C:\Program Files\PostgreSQL\13\data